function submit()
  addpath('./lib');

<<<<<<< HEAD
  conf.assignmentSlug = 'support-vector-machines';
  conf.itemName = 'Support Vector Machines';
  conf.partArrays = { ...
    { ...
      '1', ...
      { 'gaussianKernel.m' }, ...
      'Gaussian Kernel', ...
    }, ...
    { ...
      '2', ...
      { 'dataset3Params.m' }, ...
      'Parameters (C, sigma) for Dataset 3', ...
    }, ...
    { ...
      '3', ...
      { 'processEmail.m' }, ...
      'Email Preprocessing', ...
    }, ...
    { ...
      '4', ...
      { 'emailFeatures.m' }, ...
      'Email Feature Extraction', ...
=======
  conf.assignmentSlug = 'multi-class-classification-and-neural-networks';
  conf.itemName = 'Multi-class Classification and Neural Networks';
  conf.partArrays = { ...
    { ...
      '1', ...
      { 'lrCostFunction.m' }, ...
      'Regularized Logistic Regression', ...
    }, ...
    { ...
      '2', ...
      { 'oneVsAll.m' }, ...
      'One-vs-All Classifier Training', ...
    }, ...
    { ...
      '3', ...
      { 'predictOneVsAll.m' }, ...
      'One-vs-All Classifier Prediction', ...
    }, ...
    { ...
      '4', ...
      { 'predict.m' }, ...
      'Neural Network Prediction Function' ...
>>>>>>> 31fb6aa141f3e43a0681249c444197935114e850
    }, ...
  };
  conf.output = @output;

  submitWithConfiguration(conf);
end

<<<<<<< HEAD
function out = output(partId, auxstring)
  % Random Test Cases
  x1 = sin(1:10)';
  x2 = cos(1:10)';
  ec = 'the quick brown fox jumped over the lazy dog';
  wi = 1 + abs(round(x1 * 1863));
  wi = [wi ; wi];
  if partId == '1'
    sim = gaussianKernel(x1, x2, 2);
    out = sprintf('%0.5f ', sim);
  elseif partId == '2'
    load('ex6data3.mat');
    [C, sigma] = dataset3Params(X, y, Xval, yval);
    out = sprintf('%0.5f ', C);
    out = [out sprintf('%0.5f ', sigma)];
  elseif partId == '3'
    word_indices = processEmail(ec);
    out = sprintf('%d ', word_indices);
  elseif partId == '4'
    x = emailFeatures(wi);
    out = sprintf('%d ', x);
=======
function out = output(partId, auxdata)
  % Random Test Cases
  X = [ones(20,1) (exp(1) * sin(1:1:20))' (exp(0.5) * cos(1:1:20))'];
  y = sin(X(:,1) + X(:,2)) > 0;
  Xm = [ -1 -1 ; -1 -2 ; -2 -1 ; -2 -2 ; ...
          1 1 ;  1 2 ;  2 1 ; 2 2 ; ...
         -1 1 ;  -1 2 ;  -2 1 ; -2 2 ; ...
          1 -1 ; 1 -2 ;  -2 -1 ; -2 -2 ];
  ym = [ 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 ]';
  t1 = sin(reshape(1:2:24, 4, 3));
  t2 = cos(reshape(1:2:40, 4, 5));

  if partId == '1'
    [J, grad] = lrCostFunction([0.25 0.5 -0.5]', X, y, 0.1);
    out = sprintf('%0.5f ', J);
    out = [out sprintf('%0.5f ', grad)];
  elseif partId == '2'
    out = sprintf('%0.5f ', oneVsAll(Xm, ym, 4, 0.1));
  elseif partId == '3'
    out = sprintf('%0.5f ', predictOneVsAll(t1, Xm));
  elseif partId == '4'
    out = sprintf('%0.5f ', predict(t1, t2, Xm));
>>>>>>> 31fb6aa141f3e43a0681249c444197935114e850
  end 
end
